     <div class="pagination pagination-centered">
        <ul class="paginator-offdays">
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('vpbxui/settings/offdays', array('page' => $this->first, 'order_by' => $order_by, 'order' => $order, ),array('query'=>array('startdate'=>$startdate, 'enddate'=>$enddate, 'itemsperpage'=>$itemsperpage))); ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('vpbxui/settings/offdays', array('page' => $this->previous, 'order_by' => $order_by, 'order' => $order, ),array('query'=>array('startdate'=>$startdate, 'enddate'=>$enddate,'itemsperpage'=>$itemsperpage))); ?>">&lsaquo;</a></li>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url('vpbxui/settings/offdays', array('page' => $page, 'order_by' => $order_by, 'order' => $order, ),array('query'=>array('startdate'=>$startdate, 'enddate'=>$enddate,'itemsperpage'=>$itemsperpage))); ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('vpbxui/settings/offdays', array('page' => $this->next, 'order_by' => $order_by, 'order' => $order,) ,array('query'=>array('startdate'=>$startdate, 'enddate'=>$enddate,'itemsperpage'=>$itemsperpage))); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('vpbxui/settings/offdays', array( 'page' => $this->last, 'order_by' => $order_by, 'order' => $order, ),array('query'=>array('startdate'=>$startdate, 'enddate'=>$enddate, 'itemsperpage'=>$itemsperpage))); ?>">&raquo;</a></li>
        </ul>
    </div>
 