     <div class="pagination pagination-centered">
        <ul class="paginator-cdr">
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('vpbxui/cdr', array('page' => $this->first, 'order_by' => $order_by, 'order' => $order,'like_by'=>$like_by, 'like'=> $like),array('query'=>array('scope'=>$scope,'filters'=>$filters))); ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('vpbxui/cdr', array('page' => $this->previous, 'order_by' => $order_by, 'order' => $order,'like_by'=>$like_by, 'like'=> $like),array('query'=>array('scope'=>$scope,'filters'=>$filters))); ?>">&lsaquo;</a></li>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url('vpbxui/cdr', array('page' => $page, 'order_by' => $order_by, 'order' => $order, 'like_by'=>$like_by, 'like'=> $like),array('query'=>array('scope'=>$scope, 'filters'=>$filters))); ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('vpbxui/cdr', array('page' => $this->next, 'order_by' => $order_by, 'order' => $order, 'like_by'=>$like_by, 'like'=> $like),array('query'=>array('scope'=>$scope,'filters'=>$filters))); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('vpbxui/cdr', array( 'page' => $this->last, 'order_by' => $order_by, 'order' => $order, 'like_by'=>$like_by, 'like'=> $like),array('query'=>array('scope'=>$scope,'filters'=>$filters))); ?>">&raquo;</a></li>
        </ul>
    </div>
 