<?php

$title = 'Удалить профиль абонента';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<p>Подтвердите удаление внутреннего номера
   <b><?php echo $this->escapeHtml($extensionprofile->profilename); ?></b> 
</p>
<?php
$url = $this->url('vpbxui/settings/profile/internal', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $extensionprofile->id; ?>" />
    <input type="submit" name="del" value="Да" />
    <input type="submit" name="del" value="Нет" />
</div>
</form>