<ul class="nav">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if( ! $hasChildren): ?>
        <li <?php if($page->isActive()) echo 'class="active"'?>>
            <a class="nav-header" href="<?php echo $page->getHref() ?>">
                <?php echo $this->translate($page->getLabel()) ?>
            </a>
        </li>
        <?php else: ?>
        <li  class="dropdown<?php echo ($this->navigation()->findActive($page))?' active':'';?>">
            <a  class="dropdown-toggle" href="<?php echo $page->getHref();?>" data-hover="dropdown" data-delay="50" data-close-others="false">
                <span><?php echo $this->translate($page->getLabel()) ?></span>
            </a>

            <ul class="dropdown-menu" id="page_<?php echo $count ?>">
            <?php foreach($page->getPages() as $child): ?>
                <?php // when using partials we need to manually check for ACL conditions ?>
                <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                <li>
                    <a href="<?php echo $child->getHref() ?>">
                        <?php echo $this->translate($child->getLabel()) ?>
                    </a>
                </li>
            <?php endforeach ?>
            </ul>
            
           <?php endif ?>
        <?php $count++ ?>
    <?php endforeach ?>
    
      
                        
         </li>   
        
    <?php if ($this->zfcUserIdentity()): ?>
         <li class="dropdown">
             <a href="<?php echo $this->url('zfcuser/logout')?>" title="выход"><i class="icon-off"></i></a>
       </li> 
    <?php endif;?> 
    
</ul>