<?php

$title = 'Редактирование алиаса Skype';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'vpbxui/settings/skypealias',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
 
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();