<?php
// module/Vpbxui/view/internal/skype-alias/index.phtml:

$title = 'Алиасы Skype';
$this->headTitle($title);
?> 
 <table class="table table-striped table-bordered table-condensed table-hover">
<tr class="tblheader">
 <th>Наименование</th>
 <th>Номер</th>
        <th>Skype ID</th>           
        <th>Комментарий</th>
    <th>&nbsp;</th>
</tr>
 <?php foreach ($skypealiases as $skypealias) : 
 ?>
 
<tr class="tblcontent">    

<td class="content"><a href="<?php echo $this->url('vpbxui/settings/skypealias',
            array('action'=>'edit', 'id' => $skypealias->id));?>"><?php echo $this->escapeHtml($skypealias->custname);?></a></td>
             

    <td class="content"><a href="<?php echo $this->url('vpbxui/settings/skypealias',
            array('action'=>'edit', 'id' => $skypealias->id));?>"><?php echo $this->escapeHtml($skypealias->number);?></a></td>
             

    <td class="content"><img src="/img/skype-small.png">&nbsp<a href="<?php echo $this->url('vpbxui/settings/skypealias',
            array('action'=>'edit', 'id' => $skypealias->id));?>"><?php echo $this->escapeHtml($skypealias->skypeid);?></a></td>

	<td class="content"><a href="<?php echo $this->url('vpbxui/settings/skypealias',
            array('action'=>'edit', 'id' => $skypealias->id));?>"><?php echo $this->escapeHtml($skypealias->custdesc);?></a></td>
             
    
    <td>
         <a href="<?php echo $this->url('vpbxui/settings/skypealias',
            array('action'=>'edit', 'id' => $skypealias->id));?>">изменить</a>
            &nbsp
        <a href="<?php echo $this->url('vpbxui/settings/skypealias',
            array('action'=>'delete', 'id' => $skypealias->id));?>">удалить</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
  