<?php
$formRenderer = $this->formRenderer($form, 'renderer.bootstrap', 'vertical');

 ?><div class="container-fluid inline frameddiv">
    <div class="row-fluid">
        <div class="span4"><u><?php
        echo $name;?></u><?php        
?><div><div class="inline"><?php        
echo $this->formRow($starttime);
?></div><div class="inline"><?php
echo $this->formRow($endtime);
?></div></div><?php

echo isset($active)?$this->formRow($active):'';

?></div>
</div>
</div>
<?php
