<?php

/* module/Vpbxui/view/internal/pickup-group/add.phtml */

$title = 'Добавить новую группу перехвата';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('vpbxui/settings/groups/pickup', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);

 echo $this->formCollection($form);
echo $this->form()->closeTag();
  