<?php
/** module/Vpbxui/view/call-centre-stat/index.phtml **/

$title = 'статистика по колл-центру';
$this->headTitle($title);
$operatorsurl = $this->url('vpbxui/callcentre/stats/operators');
$operatorsmissedgrid = $this->url('vpbxui/callcentre/stats/operators/missed')."#grid";
?>
 <div id ="ccstat">
<table id="ccstattable" class="table table-striped table-bordered table-condensed">
        <tr><th>&nbsp</th>
        <th><a href="<?php echo $operatorsurl;?>#24hrs">24 часа</a></th>
        <th><a href="<?php echo $operatorsurl;?>#30days">30 дней</a></th>
        <th><a href="<?php echo $operatorsurl;?>#integral">интегрально</a></th></tr>       
          <tr>
          <td class="cell-bold content">принято</td>           
          <td class="content"><?php echo $ccstat->total24hrs - $ccstat->missed24hrs;?></td>
          <td class="content"><?php echo $ccstat->total30days - $ccstat->missed30days;?></td>
          <td class="content"><?php echo $ccstat->totalintegral - $ccstat->missedintegral;?></td>                    
          </tr>
          <tr>
          <td class="cell-bold content">пропущено</td>
          <td class="content"><a href="<?php echo $operatorsmissedgrid?>"><?php echo $ccstat->missed24hrs;?></a></td>
          <td class="content"><a href="<?php echo $operatorsmissedgrid?>"><?php echo $ccstat->missed30days;?></a></td>
          <td class="content"><a href="<?php echo $operatorsmissedgrid?>"><?php echo $ccstat->missedintegral;?></a></td>
          </tr>
          <tr>
          <td class="cell-bold cell-underlined content">всего</td>
          <td class="content"><?php echo $ccstat->total24hrs;?></td>
          <td class="content"><?php echo $ccstat->total30days;?></td>
          <td class="content"><?php echo $ccstat->totalintegral;?></td>
          </tr>
</table>
 </div>
 <br>
 <br><sub><ul>
<li>
учитываются только вызовы длительностью более 7 секунд c момент направления в колл-центр (активируется после 3-х секундной задержки с момента поступления на номер сети ТФОП)
</li>
</ul>
</sub>