<?php

$title = 'Удалить контекст';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<p>Подтвердите удаление контекста
   <b><?php echo $this->escapeHtml($context->custname); ?></b> 
</p>
<?php
$url = $this->url('vpbxui/settings/context', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $context->id; ?>" />
    <input type="submit" name="del" value="Да" />
    <input type="submit" name="del" value="Нет" />
</div>
</form>