<?php

$title = 'выбор номера ';
$this->headTitle($title);

$form = $this->form;
?><div><h1 id="largedid"></h1></div><?php  
 echo $this->form()->openTag($form);
?> 
<fieldset>
    <legend>выбор номера телефона для тестирования</legend>
<div class="container">
  <div id="rowcont" class="row">
 </div>
   </div>
   <div>
 </div><div class="nextform"><?php
 ?>
</div>
</fieldset>
<?php
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag($form);
?>
 