<?php

$title = 'выбор номера ';
$this->headTitle($title);

$form = $this->form;
 ?>
 <h4>Шаг 1. Выбор номера.</h4>
 <?php 
 echo $this->form()->openTag($form);
?> 
<fieldset>
    <legend>выбор номера телефона для тестирования</legend>
<div class="container">
  <div id="rowcont" class="row">
 </div>
   </div>
   <div>
 </div><div class="nextform"><?php
echo $this->formRow($form->get('submit'));
?>
</div>
</fieldset>
<?php
echo $this->form()->closeTag($form);
?>
 