<?php

$title = 'Загрузить новый медиа файл';
$this->headTitle($title);
 
$form = $this->form;
$form->setAttribute('action', $this->url('vpbxui/settings/media', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('custdesc'));
echo $this->formRow($form->get('mediatype'));
?>
<div class="fileupload fileupload-new" data-provides="fileupload">
  <div class="input-append">
    <div class="uneditable-input span3">
    <i class="icon-file fileupload-exists">
    </i> <span class="fileupload-preview"></span></div><span class="btn btn-file">
    <span class="fileupload-new">Выбрать файл</span>
    <span class="fileupload-exists">Поменять</span>     
<?php
echo $this->formRow($form->get('custname'));
?>
 </span><a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Очистить</a>
  </div>
</div>
<?php
echo $this->formRow($form->get('submit'));


echo $this->form()->closeTag();
 