<?php

$title = 'Удалить медиа файл';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<p>Подтвердите удаление медиа файла
   <b><?php echo $this->escapeHtml($mediarepos->custname); ?></b>
 </p>
<?php
$url = $this->url('vpbxui/settings/media', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $mediarepos->id; ?>" />
    <input type="submit" name="del" value="Да" />
    <input type="submit" name="del" value="Нет" />
</div>
</form>