<?php
// module/Vpbxui/view/internal/trunk/delete.phtml:

$title = 'Удалить транк';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<p>Подтвердите удаление транка
   <b><?php echo $this->escapeHtml($trunk->custname); ?></b> 
</p>
<?php
$url = $this->url('vpbxui/settings/trunk', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $trunk->id; ?>" />
    <input type="submit" name="del" value="Да" />
    <input type="submit" name="del" value="Нет" />
</div>
</form>