<?php
echo $this->headScript()
 		  ->appendFile($this->basePath() .   '/js/select2.custom.js')
;
?>

<div>
<ol>
<li>Выбрать допустимый диапазон внутренней нумерации</li>
<li>Добавить внутренние номера для обычных сотрудников</li>
<li>Добавить внутренние номера для операторов колл-центра - на данных сотрудников будут распределятся вызовы в рабочее время (в случае если абонент позвонивший на внешнюю линию не донабрал внутреннего абонента в течение паузы-задержки, предназначенной для донабора внутреннего номера)</li>
</ol>
</div>
<div class="wizdataintnum" data-url="<?php echo $this->url('internalapi')?>">

<div class="submitable">
<?php echo $this->form()->openTag($this->numbersallowedform);?>
<?php echo $this->form($this->numbersallowedform);?>
<?php echo $this->form()->closeTag();?>
</div>
<p>Внутренние номера обычных сотрудников: </p>
<?php echo $this->form($this->regularinternallistform);?>
<p>Внутренние номера операторов колл-центра:</p> 
<?php echo $this->form($this->ccoperatorlistform);?>
 </div>