<?php
echo $this->headScript()
 		  ->appendFile($this->basePath() .   '/js/select2.custom.js')
;
?>
 
<form id="numbersallowed">
  <input type="checkbox" name="chk_group[]" value="100" />100-199 
<input type="checkbox" name="chk_group[]" value="200" />200-299 
<input type="checkbox" name="chk_group[]" value="300" checked />300-399 
<input type="checkbox" name="chk_group[]" value="400" />400-499 
<input type="checkbox" name="chk_group[]" value="500" />500-399 
<input type="checkbox" name="chk_group[]" value="600" />600-699 
<input type="checkbox" name="chk_group[]" value="700" />700-799 
<input type="checkbox" name="chk_group[]" value="900" />900-999 
 </form>
 
 
<form id="regularinternallist" class="intlist">
 <select id="regularinternallistselect">
    </select>
</form>
 
 <form id="ccoperatorlist" class="intlist">
 <select id="ccoperatorselect">
    </select>
</form>
 
 