<li><?php echo $this->title?>
<div class="fileupload fileupload-new" data-provides="fileupload">
  <div class="input-append">
    <div class="uneditable-input span3">
    <i class="icon-file fileupload-exists">
    </i> <span class="fileupload-preview"></span></div><span class="btn btn-file">
    <span class="fileupload-new">Выбрать файл</span>
    <span class="fileupload-exists">Поменять</span>     
<?php
echo $this->element;
?>
 </span><a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Очистить</a>
  </div>
</div>
</li>