 <div class="jpcontainer">
  <div class="jp-jplayer1" data-defaultsound="<?php echo $this->defaultSound?>" data-indexnum="<?php echo $this->indexNum?>"></div>
 
  <div id="jp_container_<?php echo $this->indexNum?>" class="jp-audio">
 
    <div class="jp-type-single">
  
      <div class="jp-gui jp-interface">
        <ul class="jp-controls">
          <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
          <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
          <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
          <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
          <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
          <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
        </ul>
        <div class="jp-progress">
          <div class="jp-seek-bar">
            <div class="jp-play-bar"></div>
          </div>
        </div>
        <div class="jp-volume-bar">
          <div class="jp-volume-bar-value"></div>
        </div>
        <div class="jp-time-holder">
          <div class="jp-current-time"></div>
          <div class="jp-duration"></div>
          <ul class="jp-toggles">
     
          </ul>
        </div>
      </div>
      <div class="jp-title">
         <ul class="jptitle">
        <a href="#" class="uploadMediaDialog" data-formname="<?php echo $this->dataUploadInputName?>"><?php echo $media->custname?></a>
 <input class="fileupload hiddeninput" accept="audio/mp3" type="file" data-url="" name="<?php echo $this->dataUploadInputName?>" id="<?php echo $this->dataUploadInputName?>">
           </ul>
      </div>
      <div class="jp-no-solution">
        <span>Требуется обновление</span>
       </div>
    </div>
  </div>
</div>