 
<?php
echo $this->headScript()
 		  ->appendFile($this->basePath() .   '/js/jquery.ui.widget.js')
 		  ->appendFile($this->basePath() .   '/js/jquery.iframe-transport.js')
 		  ->appendFile($this->basePath() .   '/js/jquery.fileupload.js')
 		  	
;
var_dump($media);
?>
<br>
<br>
 
<ol>
<li>Приветствия:</li>
<ul>
<li>рабочего дня - используется в рабочее время <div><input id="wtgreeting" class="fileupload" type="file" name="wtgreeting" data-url=""></div> </li>
<li>нерабочего дня - используется в нерабочее время <div><input id="wegreeting" class="fileupload"  type="file" name="wegreeting" data-url=""></div> </li>
</ul>
<br>
<li>Мелодии:</li>
<ul>
<li>вызова - используется вместо сигнала КПВ при входящих вызовах  <div><input id="ringingbacktone" class="fileupload" type="file" name="ringingbacktone" data-url=""></div></li>
<li>на удержание - используется при использовании услуги удержания вызова <div><input id="musiconhold" type="file" class="fileupload"  name="musiconhold" data-url=""> </div></li>
</ul>
<ol>
 	<br>
<br>
 
<div class="wizardbuttom">
<button class="btn btn-primary" onclick="location.href='<?php echo $this->url('wizard',array('action'=>'step3'))?>'">далее</button>
</div>
 	
  <script>
$(function () {
    $('.fileupload').fileupload({
        dataType: 'json',
        done: function (e, data) {
            	if (null===data.result.file.name)
            	{
                	alert('ошибка загрузки!');
                }
            	else
            	{
                  $('#'+e.target.id).replaceWith('<a href="">'+data.result.file.name+'</a>');    
            	}
        }
    });
});
</script>
 