<?php

$title = 'Перезагрузка станции';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<p>Подтвердите перезагрузку станции (внимание - перезагрузка приведет к тому, что совершаемые в данный момент разговоры абонентов будут прерваны, а записи о них потеряны)
    
</p>
<?php
$url = $this->url('vpbxui/callcentre/monitoring', array(
    'action' => 'restart'
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="submit" name="del" value="Да" />
    <input type="submit" name="del" value="Нет" />
</div>
</form>