<?php

$title = 'Редактирование свойств группы абонентов';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'vpbxui/settings/groups/internal',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
 
echo $this->partial('extensionGroupFormPartial.phtml',array('form' => $form));
