<?php
// module/Vpbxui/view/internal/internal/index.phtml:

$title = 'Внутренние номера';
$this->headTitle($title);
?>
  
 
 <table class="table table-striped table-bordered table-condensed table-hover">
<tr class="tblheader">
 <th>Номер</th>
         <th>Имя сотрудника</th>
         <th>Группа</th>
        <th>Комментарий</th>           
    <th>&nbsp;</th>
</tr>
<?php $extensiontypeimg = array('regular'=>'/img/extension-regular.png','operator'=>'/img/extension-operator.png')?>

 <?php foreach ($extensions as $extension) : ?>
<tr class="tblcontent">
    <td class="content"><img src="<?php echo $extensiontypeimg[$extension->extensiontype];?>"><a class="extensionnumber" href="<?php echo $this->url('vpbxui/internal',
            array('action'=>'edit', 'id' => $extension->id));?>"><?php echo $this->escapeHtml($extension->extension);?></a></td>
            

    <td class="content"><a href="<?php echo $this->url('vpbxui/internal',
            array('action'=>'edit', 'id' => $extension->id));?>"><?php echo $this->escapeHtml($extension->custname);?></a></td>
<td class="content"><a href="<?php echo $this->url('vpbxui/settings/groups/internal',
            array('action'=>'edit', 'id' => $extension->extensiongroup));?>" target="_blank"><?php echo $this->escapeHtml($extensiongroups[$extension->extensiongroup]);?></a></td>            
        <td class="content"><a href="<?php echo $this->url('vpbxui/internal',
            array('action'=>'edit', 'id' => $extension->id));?>"><?php echo $this->escapeHtml($extension->custdesc);?></a></td>
    
    <td class="content">
        <a href="<?php echo $this->url('vpbxui/internal',
            array('action'=>'edit', 'id' => $extension->id));?>">изменить<!--<img src="/img/basket.png">--></a>
            &nbsp
        <a href="<?php echo $this->url('vpbxui/internal',
            array('action'=>'delete', 'id' => $extension->id));?>">удалить<!--<img src="/img/basket.png">--></a>
    </td>
</tr>
<?php endforeach; ?>
</table>

