<?php

$title = 'Профили групп абонентов';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

 <table class="table table-striped table-bordered table-condensed table-hover">
<tr class="tblheader">
     <th>Наименование</th>
     <th>Комментарий</th>
    <th>&nbsp;</th>
</tr>
 <?php foreach ($extensionprofilegroups as $extensionprofilegroup) : ?>
<tr class="tblcontent">

    <td class="content">
    <a href="<?php echo $this->url('vpbxui/settings/profile/group',
            array('action'=>'edit', 'id' => $extensionprofilegroup->id));?>">
    
    <?php echo $this->escapeHtml($extensionprofilegroup->profilename);?></a>
    
    </td>
    
    <td class="content">
    <a href="<?php echo $this->url('vpbxui/settings/profile/group',
            array('action'=>'edit', 'id' => $extensionprofilegroup->id));?>">
    
    <?php echo $this->escapeHtml($extensionprofilegroup->profiledesc);?></a>
    
    </td>
    
       
    <td>
         
        <a href="<?php echo $this->url('vpbxui/settings/profile/group',
            array('action'=>'delete', 'id' => $extensionprofilegroup->id));?>"><img src="/img/basket.png"></a>
    </td>
</tr>
<?php endforeach; ?>
</table>
