<?php

$title = 'Применить новые настройки безопасности';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<p>Применить новые настройки безопасности к уже введенным в систему абонентам (нет - только для новых):
 </p>
<?php
$url = $this->url('vpbxui/settings/defaultdenypermit', array(
    'action' => 'prune',
 ));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
     <input type="submit" name="prune" value="Да" />
    <input type="submit" name="prune" value="Нет" />
</div>
</form>